reference: "ref/2R.chr"

populations:
  - pop1
  - pop2

fastq_dir: "samples"

# mapping parameters
bwa_threads: 8
bwa_aln_params: "-n 0.01 -l 100 -o 1 -d 12 -e 12"

# mpileup options
mpileup_min_qual: 20

# popoolation2 parameters
min_count: 3
min_cov: 30
max_cov: 200
pool_size: 100
