reference: "ref/GCF_001465965.1_Pdom_r1.2_genomic.fna"

populations:
  - AAA9495
  - AAB7105

fastq_dir: "samples"

# mapping parameters
bwa_threads: 64
bwa_aln_params: "-n 0.01 -l 100 -o 1 -d 12 -e 12"

# mpileup options
mpileup_min_qual: 20

# popoolation2 parameters
min_count: 3
min_cov: 40
max_cov: 200
pool_size: 54
